# ===============================
# CẤU HÌNH SERVER
# ===============================
server.port=8080

# ===============================
# CẤU HÌNH DATABASE (MYSQL)
# ===============================
# Nhớ tạo sẵn database tên là qlkh_cdda trong MySQL trước khi chạy nhé
spring.datasource.url=jdbc:mysql://localhost:3306/qlkh_cdda?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
# Điền password MySQL của bạn vào đây (nếu dùng XAMPP thì để trống)
spring.datasource.password=thanh123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CẤU HÌNH HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# CẤU HÌNH JWT (JSON WEB TOKEN)
# ===============================
jwt-secret=KhoaBiMatCuaThanhChoHeThongQuanLyKhoaHocVaChamDiemDoAn2026PTIT

# Access token sống 1 tiếng (3600000 ms)
jwt-expire=3600000

# Refresh token sống 7 ngày (604800000 ms)
jwt-refresh-expire=604800000